---
- name: Backup running config
  hosts: cisco
  gather_facts: false
  connection: network_cli

  vars:
    student_id: "66070084"
    output_file: "{{ playbook_dir }}/show_run_{{ student_id }}_{{ inventory_hostname }}.txt"
    ansible_connect_timeout: 30
    ansible_command_timeout: 120
    ansible_ssh_retries: 2

  tasks:
    - name: Collect running configuration
      cisco.ios.ios_command:
        commands:
          - terminal length 0
          - show running-config
        wait_for:
          - result[1] contains version
        match: all
      register: show_run

    - name: Save running configuration locally
      ansible.builtin.copy:
        dest: "{{ output_file }}"
        content: "{{ (show_run.stdout is string) | ternary(show_run.stdout, show_run.stdout | join('\n')) }}"
        mode: "0644"
      delegate_to: localhost
      run_once: true